# Site settings
title: cryptopixelspace
email: cryptopixelspace@outlook.com
url: https://opensea.io/CryptoPixelSpace
description: "CryptoPixelSpace is an open game based on blockchain and metaverse. Her NFT holders can import their NFTs into the game and customize exclusive characters."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: CryptoPixelSpace

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/CryptoPixelSP
  - title: opensea
    url: https://opensea.io/CryptoPixelSpace
  - title: github
    url: https://github.com/CryptoPixelSpace

# Build settings
markdown: kramdown
permalink: pretty
